use std::cell::RefCell;
use std::rc::Rc;

use ipc_messages::webrtc::{PeerConnectionId, TrackKind, TransceiverId};
use js_engine::gc_struct;
use js_engine::{Completion, ExecutionContext, JsTypes};

use crate::dom::event::{EventTarget, EventTargetAccess};
use crate::dom::fire_event;
use crate::js::Types;
use crate::webidl::bindings::create_interface_instance;

type JsObject = <Types as JsTypes>::JsObject;

/// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrackstate>
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum MediaStreamTrackState {
    Live,
    Ended,
}

impl MediaStreamTrackState {
    pub(crate) fn as_idl(self) -> &'static str {
        match self {
            Self::Live => "live",
            Self::Ended => "ended",
        }
    }
}

/// <https://w3c.github.io/mediacapture-main/#dfn-source>
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum TrackSource {
    /// A capture device of the user agent.
    Capture { device_id: String },
    /// The media a remote peer sends on one transceiver.
    /// <https://w3c.github.io/webrtc-pc/#dfn-create-an-rtcrtpreceiver>
    Remote {
        peer: PeerConnectionId,
        transceiver: TransceiverId,
    },
}

/// The internal slots of a MediaStreamTrack, shared by every clone of it.
#[derive(Debug)]
pub(crate) struct TrackSlots {
    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-id>
    pub(crate) id: String,
    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-kind>
    pub(crate) kind: TrackKind,
    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-label>
    pub(crate) label: String,
    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-enabled>
    pub(crate) enabled: bool,
    /// <https://w3c.github.io/mediacapture-main/#track-muted>
    pub(crate) muted: bool,
    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-readystate>
    pub(crate) ready_state: MediaStreamTrackState,
    /// <https://w3c.github.io/mediacapture-main/#dfn-source>
    pub(crate) source: TrackSource,
}

/// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack>
#[gc_struct]
pub(crate) struct MediaStreamTrack {
    /// The track's EventTarget base.
    pub(crate) event_target: EventTarget,

    #[ignore_trace]
    pub(crate) slots: Rc<RefCell<TrackSlots>>,
}

impl EventTargetAccess for MediaStreamTrack {
    fn get_event_target(&self, _ec: &mut dyn ExecutionContext<Types>) -> EventTarget {
        self.event_target.clone()
    }
}

/// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-id>
fn generate_track_id() -> String {
    // The identifier is generated by the User Agent and is unique within
    // the browsing session.
    uuid::Uuid::new_v4().to_string()
}

impl MediaStreamTrack {
    /// <https://w3c.github.io/mediacapture-main/#dfn-create-a-mediastreamtrack>
    pub(crate) fn create(
        source: TrackSource,
        kind: TrackKind,
        label: String,
        muted: bool,
        ec: &mut dyn ExecutionContext<Types>,
    ) -> Completion<Self, Types> {
        // Step 1: Let track be a new MediaStreamTrack object.
        // Step 2: Set track.[[Source]] to source.
        // Step 3: Set track.[[Kind]] to kind.
        // Step 4: Set track.[[Id]] to the result of generating an identifier.
        // Step 5: Set track.[[Label]] to label.
        // Step 6: Set track.[[ReadyState]] to "live".
        // Step 7: Set track.[[Enabled]] to true.
        // Step 8: Set track.[[Muted]] to true if source is muted, and false
        // otherwise.
        let track = Self {
            event_target: EventTarget::new(ec),
            slots: Rc::new(RefCell::new(TrackSlots {
                id: generate_track_id(),
                kind,
                label,
                enabled: true,
                muted,
                ready_state: MediaStreamTrackState::Live,
                source,
            })),
        };

        // Step 9: Return track.
        // Note: The platform object is created here so the track has its
        // reflector before an algorithm hands it to script.
        let object = create_interface_instance::<Types, MediaStreamTrack>(track, ec)?;
        ec.with_object_any(&object)
            .and_then(|data| data.downcast_ref::<MediaStreamTrack>().cloned())
            .ok_or_else(|| ec.new_type_error("MediaStreamTrack instance is not a MediaStreamTrack"))
    }

    /// The track's platform object.
    pub(crate) fn object(&self) -> Option<JsObject> {
        self.event_target.reflector.clone()
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-id>
    pub(crate) fn id(&self) -> String {
        self.slots.borrow().id.clone()
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-kind>
    pub(crate) fn kind(&self) -> TrackKind {
        self.slots.borrow().kind
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-kind>
    pub(crate) fn kind_idl(&self) -> &'static str {
        match self.kind() {
            TrackKind::Audio => "audio",
            TrackKind::Video => "video",
        }
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-label>
    pub(crate) fn label(&self) -> String {
        self.slots.borrow().label.clone()
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-enabled>
    pub(crate) fn enabled(&self) -> bool {
        self.slots.borrow().enabled
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-enabled>
    pub(crate) fn set_enabled(&self, enabled: bool) {
        // On setting, it MUST set the track's [[Enabled]] to the new value.
        self.slots.borrow_mut().enabled = enabled;
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-muted>
    pub(crate) fn muted(&self) -> bool {
        self.slots.borrow().muted
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-readystate>
    pub(crate) fn ready_state(&self) -> MediaStreamTrackState {
        self.slots.borrow().ready_state
    }

    pub(crate) fn source(&self) -> TrackSource {
        self.slots.borrow().source.clone()
    }

    /// <https://w3c.github.io/mediacapture-main/#set-track-muted>
    pub(crate) fn set_a_tracks_muted_state(
        &self,
        new_state: bool,
        time_millis: f64,
        ec: &mut dyn ExecutionContext<Types>,
    ) -> Completion<(), Types> {
        // Step 1: Let track be the MediaStreamTrack in question.
        // Step 2: Set track.[[Muted]] to newState.
        let changed = {
            let mut slots = self.slots.borrow_mut();
            let changed = slots.muted != new_state;
            slots.muted = new_state;
            changed
        };
        // Note: The event fires only on a change (the caller's "if muted
        // differs" checks).
        if !changed {
            return Ok(());
        }

        // Step 3: If newState is true let eventName be mute, otherwise
        // unmute.
        let event_name = if new_state { "mute" } else { "unmute" };

        // Step 4: Fire an event named eventName on track.
        fire_event(ec, self, event_name, time_millis, false)?;
        Ok(())
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-stop>
    pub(crate) fn stop(&self) {
        // Step 1: Let track be the current MediaStreamTrack object.
        // Step 2: If track.[[ReadyState]] is "ended", then abort these steps.
        let mut slots = self.slots.borrow_mut();
        if slots.ready_state == MediaStreamTrackState::Ended {
            return;
        }

        // Step 3: Notify track.[[Source]] that track is ended.
        // Note: The user agent owns the source; it learns of a stopped
        // capture track when the track is removed from its senders.
        // Step 4: Set track.[[ReadyState]] to "ended".
        slots.ready_state = MediaStreamTrackState::Ended;
    }

    /// <https://w3c.github.io/mediacapture-main/#ends-nostop>
    pub(crate) fn ended_for_a_reason_other_than_stop(
        &self,
        time_millis: f64,
        ec: &mut dyn ExecutionContext<Types>,
    ) -> Completion<(), Types> {
        // Step 1: If the track's [[ReadyState]] is "ended", abort these
        // steps.
        {
            let mut slots = self.slots.borrow_mut();
            if slots.ready_state == MediaStreamTrackState::Ended {
                return Ok(());
            }

            // Step 2: Set the track's [[ReadyState]] to "ended".
            slots.ready_state = MediaStreamTrackState::Ended;
        }

        // Step 3: Notify the track's [[Source]] that the track is ended.
        // Step 4: Fire an event named ended at the track.
        fire_event(ec, self, "ended", time_millis, false)?;
        Ok(())
    }

    /// <https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-clone>
    pub(crate) fn clone_track(
        &self,
        ec: &mut dyn ExecutionContext<Types>,
    ) -> Completion<Self, Types> {
        // Step 1: Let trackClone be the result of cloning a track given
        // this.
        // Cloning a track: Let trackClone be the result of creating a
        // MediaStreamTrack with track.[[Source]], track.[[Kind]] and
        // track.[[Label]]; set trackClone.[[ReadyState]] to
        // track.[[ReadyState]]; set trackClone.[[Enabled]] to
        // track.[[Enabled]]; set trackClone.[[Muted]] to track.[[Muted]].
        let (source, kind, label, ready_state, enabled, muted) = {
            let slots = self.slots.borrow();
            (
                slots.source.clone(),
                slots.kind,
                slots.label.clone(),
                slots.ready_state,
                slots.enabled,
                slots.muted,
            )
        };
        let track_clone = Self::create(source, kind, label, muted, ec)?;
        {
            let mut slots = track_clone.slots.borrow_mut();
            slots.ready_state = ready_state;
            slots.enabled = enabled;
        }

        // Step 2: Return trackClone.
        Ok(track_clone)
    }
}
