namespace FormalWeb

/-- A finite trace of labeled transitions generated by a partial step function. -/
inductive TransitionTrace
    {State Action : Type}
    (step : State -> Action -> Option State) :
    State -> List Action -> State -> Prop where
  | nil
      (state : State) :
      TransitionTrace step state [] state
  | cons
      {start intermediate finish : State}
      {action : Action}
      {actions : List Action}
      (hstep : step start action = some intermediate)
      (htrace : TransitionTrace step intermediate actions finish) :
      TransitionTrace step start (action :: actions) finish

namespace TransitionTrace

theorem single
    {State Action : Type}
    {step : State -> Action -> Option State}
    {start finish : State}
    {action : Action}
    (hstep : step start action = some finish) :
    TransitionTrace step start [action] finish :=
  .cons hstep (.nil finish)

theorem append
    {State Action : Type}
    {step : State -> Action -> Option State}
    {start intermediate finish : State}
    {actions1 actions2 : List Action}
    (hleft : TransitionTrace step start actions1 intermediate)
    (hright : TransitionTrace step intermediate actions2 finish) :
    TransitionTrace step start (actions1 ++ actions2) finish := by
  induction hleft with
  | nil _ =>
      simpa using hright
  | @cons start intermediate next action actions hstep htrace ih =>
      simpa using TransitionTrace.cons hstep (ih hright)

end TransitionTrace

end FormalWeb
